name: paml_backend_vania
description: Sample Vania backend web application framework
version: 1.0.0

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  vania: ^0.4.0
  intl: ^0.17.0
  mysql1: ^0.20.0
  jwt_decoder: 2.0.1
  flutter_dotenv: 5.2.1


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

dependency_overrides:
  pointycastle: 3.7.3